@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.monkeybiznec.veilshadows.client.render.post;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;